# Local Development - Access host services + Hot Reload
# Use this when you need the browser to access services running on your machine
# (e.g., localhost:3000 web app for testing with AI agents)
#
# Linux:       docker compose -f compose.local.yml up --build
# macOS/Win:   docker compose -f compose.local.yml up --build
#              (use http://host.docker.internal:PORT to access host services)

services:
  browser-pool:
    build:
      context: .
      dockerfile: Dockerfile
    # Use dev supervisord config with hot reload
    command: ["supervisord", "-c", "/app/docker/supervisord.dev.conf"]
    # Linux: host networking lets browser access localhost directly
    # macOS/Windows: falls back to bridge, use host.docker.internal
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_BROWSERS=${MAX_BROWSERS:-5}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - COMMAND_TIMEOUT_DEFAULT=90
      - API_BASE_URL=http://localhost:18080
      # Dev resolution (overrides default 1920x1080)
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      # AI Vision (optional)
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
    volumes:
      - ./src:/app/src            # Hot reload - code changes restart services
      - ./docker:/app/docker      # Supervisord configs
      - ./screenshots:/app/screenshots
      - browser-profiles:/app/browser-profiles
      - downloads:/app/downloads
    tmpfs:
      - /tmp:noexec,nosuid,size=500m
      - /dev/shm:rw,nosuid,nodev,exec,size=4g
    shm_size: 4gb
    init: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  browser-profiles:
  downloads:
