# coding: utf-8

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DetectCoordinatesData(BaseModel):
    """
    DetectCoordinatesData
    """ # noqa: E501
    prompt: Optional[StrictStr] = Field(default=None, description="Element description used")
    bounding_box: Optional[Dict[str, Any]] = Field(default=None, description="Element bounding box {x, y, width, height}")
    click_point: Optional[Dict[str, Any]] = Field(default=None, description="Recommended click point {x, y}")
    confidence: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Detection confidence (0.0-1.0)")
    outcome_status: Optional[StrictStr] = Field(default=None, description="Machine-readable detect outcome status")
    reason: Optional[StrictStr] = Field(default=None, description="Machine-readable detect reason code")
    reason_detail: Optional[StrictStr] = Field(default=None, description="Human-readable reason detail")
    resolved_target: Optional[Dict[str, Any]] = Field(default=None, description="Resolved target details after validation or snapping")
    resolved_click_point: Optional[Dict[str, Any]] = Field(default=None, description="Validated or snapped click point {x, y}")
    snap_result: Optional[Dict[str, Any]] = Field(default=None, description="Details about any snap candidate that was applied")
    recommended_next_action: Optional[StrictStr] = Field(default=None, description="Suggested next action for callers")
    screenshot_url: Optional[StrictStr] = Field(default=None, description="URL to the screenshot")
    image_size: Optional[Dict[str, Any]] = Field(default=None, description="Original screenshot dimensions")
    transform_info: Optional[Dict[str, Any]] = Field(default=None, description="Coordinate transform metadata")
    debug: Optional[Dict[str, Any]] = Field(default=None, description="Optional smart-targeting debug details")
    __properties: ClassVar[List[str]] = ["prompt", "bounding_box", "click_point", "confidence", "outcome_status", "reason", "reason_detail", "resolved_target", "resolved_click_point", "snap_result", "recommended_next_action", "screenshot_url", "image_size", "transform_info", "debug"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DetectCoordinatesData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DetectCoordinatesData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prompt": obj.get("prompt"),
            "bounding_box": obj.get("bounding_box"),
            "click_point": obj.get("click_point"),
            "confidence": obj.get("confidence"),
            "outcome_status": obj.get("outcome_status"),
            "reason": obj.get("reason"),
            "reason_detail": obj.get("reason_detail"),
            "resolved_target": obj.get("resolved_target"),
            "resolved_click_point": obj.get("resolved_click_point"),
            "snap_result": obj.get("snap_result"),
            "recommended_next_action": obj.get("recommended_next_action"),
            "screenshot_url": obj.get("screenshot_url"),
            "image_size": obj.get("image_size"),
            "transform_info": obj.get("transform_info"),
            "debug": obj.get("debug")
        })
        return _obj
