# coding: utf-8

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmulateRequest(BaseModel):
    """
    EmulateRequest
    """ # noqa: E501
    action: Optional[StrictStr] = Field(default='set', description="action")
    device: Optional[StrictStr] = Field(default=None, description="device")
    device_scale_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="device_scale_factor")
    height: Optional[StrictInt] = Field(default=None, description="height")
    mobile: Optional[StrictBool] = Field(default=None, description="mobile")
    user_agent: Optional[StrictStr] = Field(default=None, description="user_agent")
    width: Optional[StrictInt] = Field(default=None, description="width")
    __properties: ClassVar[List[str]] = ["action", "device", "device_scale_factor", "height", "mobile", "user_agent", "width"]

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['set', 'clear', 'list_devices']):
            raise ValueError("must be one of enum values ('set', 'clear', 'list_devices')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmulateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmulateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action") if obj.get("action") is not None else 'set',
            "device": obj.get("device"),
            "device_scale_factor": obj.get("device_scale_factor"),
            "height": obj.get("height"),
            "mobile": obj.get("mobile"),
            "user_agent": obj.get("user_agent"),
            "width": obj.get("width")
        })
        return _obj


