# coding: utf-8

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GuiClickXYRequest(BaseModel):
    """
    GuiClickXYRequest
    """ # noqa: E501
    x: Union[StrictFloat, StrictInt] = Field(description="Screen X coordinate")
    y: Union[StrictFloat, StrictInt] = Field(description="Screen Y coordinate")
    timeframe: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mouse move duration (seconds)")
    pre_click_validate: Optional[StrictStr] = Field(default='off', description="Pre-click validation mode")
    auto_snap: Optional[StrictStr] = Field(default='off', description="Auto-snap mode for nearby targets")
    snap_radius: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum snap radius in CSS pixels")
    post_click_feedback: Optional[StrictStr] = Field(default='none', description="Post-click feedback mode")
    post_click_timeout_ms: Optional[StrictInt] = Field(default=None, description="Post-click observation timeout in milliseconds")
    return_content: Optional[StrictBool] = Field(default=False, description="Include truncated content in post-click feedback")
    content_limit_chars: Optional[StrictInt] = Field(default=None, description="Maximum returned content length")
    include_debug: Optional[StrictBool] = Field(default=False, description="Include smart-click debug diagnostics")
    __properties: ClassVar[List[str]] = ["x", "y", "timeframe", "pre_click_validate", "auto_snap", "snap_radius", "post_click_feedback", "post_click_timeout_ms", "return_content", "content_limit_chars", "include_debug"]

    @field_validator('pre_click_validate')
    def pre_click_validate_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['off', 'warn', 'strict']):
            raise ValueError("must be one of enum values ('off', 'warn', 'strict')")
        return value

    @field_validator('auto_snap')
    def auto_snap_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['off', 'nearest_clickable', 'nearest_interactive']):
            raise ValueError("must be one of enum values ('off', 'nearest_clickable', 'nearest_interactive')")
        return value

    @field_validator('post_click_feedback')
    def post_click_feedback_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'url', 'content', 'visible', 'auto']):
            raise ValueError("must be one of enum values ('none', 'url', 'content', 'visible', 'auto')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GuiClickXYRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GuiClickXYRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "x": obj.get("x"),
            "y": obj.get("y"),
            "timeframe": obj.get("timeframe"),
            "pre_click_validate": obj.get("pre_click_validate") if obj.get("pre_click_validate") is not None else 'off',
            "auto_snap": obj.get("auto_snap") if obj.get("auto_snap") is not None else 'off',
            "snap_radius": obj.get("snap_radius"),
            "post_click_feedback": obj.get("post_click_feedback") if obj.get("post_click_feedback") is not None else 'none',
            "post_click_timeout_ms": obj.get("post_click_timeout_ms"),
            "return_content": obj.get("return_content") if obj.get("return_content") is not None else False,
            "content_limit_chars": obj.get("content_limit_chars"),
            "include_debug": obj.get("include_debug") if obj.get("include_debug") is not None else False
        })
        return _obj
