# coding: utf-8

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GuiClickData(BaseModel):
    """
    GuiClickData
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="Legacy inner status")
    success: Optional[StrictBool] = Field(default=None, description="Legacy inner success flag")
    message: Optional[StrictStr] = Field(default=None, description="Legacy inner message")
    x: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Requested or resolved screen X coordinate")
    y: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Requested or resolved screen Y coordinate")
    outcome_status: Optional[StrictStr] = Field(default=None, description="Machine-readable click outcome status")
    reason: Optional[StrictStr] = Field(default=None, description="Machine-readable click reason code")
    reason_detail: Optional[StrictStr] = Field(default=None, description="Human-readable reason detail")
    precheck: Optional[Dict[str, Any]] = Field(default=None, description="Pre-click validation details")
    execution: Optional[Dict[str, Any]] = Field(default=None, description="Click execution details")
    postcheck: Optional[Dict[str, Any]] = Field(default=None, description="Post-click feedback details")
    recommended_next_action: Optional[StrictStr] = Field(default=None, description="Suggested next action for callers")
    debug: Optional[Dict[str, Any]] = Field(default=None, description="Optional smart-click debug details")
    __properties: ClassVar[List[str]] = ["status", "success", "message", "x", "y", "outcome_status", "reason", "reason_detail", "precheck", "execution", "postcheck", "recommended_next_action", "debug"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GuiClickData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GuiClickData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "success": obj.get("success"),
            "message": obj.get("message"),
            "x": obj.get("x"),
            "y": obj.get("y"),
            "outcome_status": obj.get("outcome_status"),
            "reason": obj.get("reason"),
            "reason_detail": obj.get("reason_detail"),
            "precheck": obj.get("precheck"),
            "execution": obj.get("execution"),
            "postcheck": obj.get("postcheck"),
            "recommended_next_action": obj.get("recommended_next_action"),
            "debug": obj.get("debug")
        })
        return _obj
