# coding: utf-8

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airbrowser_client.models.gui_click_data import GuiClickData

class TestGuiClickData(unittest.TestCase):
    """GuiClickData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuiClickData:
        """Test GuiClickData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GuiClickData`
        """
        model = GuiClickData()
        if include_optional:
            return GuiClickData(
                status = '',
                success = True,
                message = '',
                x = 1.337,
                y = 1.337,
                outcome_status = '',
                reason = '',
                reason_detail = '',
                precheck = airbrowser_client.models.precheck.precheck(),
                execution = airbrowser_client.models.execution.execution(),
                postcheck = airbrowser_client.models.postcheck.postcheck(),
                recommended_next_action = '',
                debug = airbrowser_client.models.debug.debug()
            )
        else:
            return GuiClickData(
        )
        """

    def testGuiClickData(self):
        """Test GuiClickData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
