# coding: utf-8

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from airbrowser_client.models.gui_click_xy_request import GuiClickXYRequest

class TestGuiClickXYRequest(unittest.TestCase):
    """GuiClickXYRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GuiClickXYRequest:
        """Test GuiClickXYRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GuiClickXYRequest`
        """
        model = GuiClickXYRequest()
        if include_optional:
            return GuiClickXYRequest(
                x = 1.337,
                y = 1.337,
                timeframe = 1.337,
                pre_click_validate = 'off',
                auto_snap = 'off',
                snap_radius = 1.337,
                post_click_feedback = 'none',
                post_click_timeout_ms = 56,
                return_content = True,
                content_limit_chars = 56,
                include_debug = True
            )
        else:
            return GuiClickXYRequest(
                x = 1.337,
                y = 1.337,
        )
        """

    def testGuiClickXYRequest(self):
        """Test GuiClickXYRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
