# coding: utf-8

# flake8: noqa

"""
    Airbrowser API

    Undetectable Chrome-in-Docker for developers and agents (REST + MCP)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BrowserApi",
    "HealthApi",
    "PoolApi",
    "ProfilesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActionResult",
    "AttributeResponse",
    "BaseResponse",
    "BrowserConfig",
    "BrowserCreated",
    "BrowserCreationData",
    "BrowserInfoResponse",
    "BrowserList",
    "BrowserListData",
    "CheckElementRequest",
    "ClickRequest",
    "CombinedDialogRequest",
    "CombinedEmulateRequest",
    "CombinedGuiClickRequest",
    "CombinedScrollRequest",
    "ConsoleLogsRequest",
    "ContentData",
    "ContentResponse",
    "CreateProfileRequest",
    "DetectCoordinatesRequest",
    "DetectCoordinatesResult",
    "ElementDataRequest",
    "ErrorResponse",
    "ExecuteData",
    "ExecuteRequest",
    "ExecuteResponse",
    "FillFormRequest",
    "FormField",
    "HealthStatus",
    "HistoryRequest",
    "LogsResponse",
    "MouseRequest",
    "NavigateRequest",
    "NetworkLogsRequest",
    "PerformanceRequest",
    "PoolScaled",
    "PoolStatusResponse",
    "PressKeysRequest",
    "ProfileInfo",
    "ProfileListData",
    "ProfileListResponse",
    "ProfileResponse",
    "ResizeRequest",
    "ScaleData",
    "ScalePool",
    "ScreenshotData",
    "ScreenshotResponse",
    "SelectRequest",
    "SnapshotRequest",
    "SuccessResponse",
    "TabsRequest",
    "TypeRequest",
    "UploadFileRequest",
    "UrlData",
    "UrlResponse",
    "WaitElementRequest",
    "WhatIsVisibleResult",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from airbrowser_client.api.browser_api import BrowserApi as BrowserApi
    from airbrowser_client.api.health_api import HealthApi as HealthApi
    from airbrowser_client.api.pool_api import PoolApi as PoolApi
    from airbrowser_client.api.profiles_api import ProfilesApi as ProfilesApi
    
    # import ApiClient
    from airbrowser_client.api_response import ApiResponse as ApiResponse
    from airbrowser_client.api_client import ApiClient as ApiClient
    from airbrowser_client.configuration import Configuration as Configuration
    from airbrowser_client.exceptions import OpenApiException as OpenApiException
    from airbrowser_client.exceptions import ApiTypeError as ApiTypeError
    from airbrowser_client.exceptions import ApiValueError as ApiValueError
    from airbrowser_client.exceptions import ApiKeyError as ApiKeyError
    from airbrowser_client.exceptions import ApiAttributeError as ApiAttributeError
    from airbrowser_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from airbrowser_client.models.action_result import ActionResult as ActionResult
    from airbrowser_client.models.attribute_response import AttributeResponse as AttributeResponse
    from airbrowser_client.models.base_response import BaseResponse as BaseResponse
    from airbrowser_client.models.browser_config import BrowserConfig as BrowserConfig
    from airbrowser_client.models.browser_created import BrowserCreated as BrowserCreated
    from airbrowser_client.models.browser_creation_data import BrowserCreationData as BrowserCreationData
    from airbrowser_client.models.browser_info_response import BrowserInfoResponse as BrowserInfoResponse
    from airbrowser_client.models.browser_list import BrowserList as BrowserList
    from airbrowser_client.models.browser_list_data import BrowserListData as BrowserListData
    from airbrowser_client.models.check_element_request import CheckElementRequest as CheckElementRequest
    from airbrowser_client.models.click_request import ClickRequest as ClickRequest
    from airbrowser_client.models.combined_dialog_request import CombinedDialogRequest as CombinedDialogRequest
    from airbrowser_client.models.combined_emulate_request import CombinedEmulateRequest as CombinedEmulateRequest
    from airbrowser_client.models.combined_gui_click_request import CombinedGuiClickRequest as CombinedGuiClickRequest
    from airbrowser_client.models.combined_scroll_request import CombinedScrollRequest as CombinedScrollRequest
    from airbrowser_client.models.console_logs_request import ConsoleLogsRequest as ConsoleLogsRequest
    from airbrowser_client.models.content_data import ContentData as ContentData
    from airbrowser_client.models.content_response import ContentResponse as ContentResponse
    from airbrowser_client.models.create_profile_request import CreateProfileRequest as CreateProfileRequest
    from airbrowser_client.models.detect_coordinates_request import DetectCoordinatesRequest as DetectCoordinatesRequest
    from airbrowser_client.models.detect_coordinates_result import DetectCoordinatesResult as DetectCoordinatesResult
    from airbrowser_client.models.element_data_request import ElementDataRequest as ElementDataRequest
    from airbrowser_client.models.error_response import ErrorResponse as ErrorResponse
    from airbrowser_client.models.execute_data import ExecuteData as ExecuteData
    from airbrowser_client.models.execute_request import ExecuteRequest as ExecuteRequest
    from airbrowser_client.models.execute_response import ExecuteResponse as ExecuteResponse
    from airbrowser_client.models.fill_form_request import FillFormRequest as FillFormRequest
    from airbrowser_client.models.form_field import FormField as FormField
    from airbrowser_client.models.health_status import HealthStatus as HealthStatus
    from airbrowser_client.models.history_request import HistoryRequest as HistoryRequest
    from airbrowser_client.models.logs_response import LogsResponse as LogsResponse
    from airbrowser_client.models.mouse_request import MouseRequest as MouseRequest
    from airbrowser_client.models.navigate_request import NavigateRequest as NavigateRequest
    from airbrowser_client.models.network_logs_request import NetworkLogsRequest as NetworkLogsRequest
    from airbrowser_client.models.performance_request import PerformanceRequest as PerformanceRequest
    from airbrowser_client.models.pool_scaled import PoolScaled as PoolScaled
    from airbrowser_client.models.pool_status_response import PoolStatusResponse as PoolStatusResponse
    from airbrowser_client.models.press_keys_request import PressKeysRequest as PressKeysRequest
    from airbrowser_client.models.profile_info import ProfileInfo as ProfileInfo
    from airbrowser_client.models.profile_list_data import ProfileListData as ProfileListData
    from airbrowser_client.models.profile_list_response import ProfileListResponse as ProfileListResponse
    from airbrowser_client.models.profile_response import ProfileResponse as ProfileResponse
    from airbrowser_client.models.resize_request import ResizeRequest as ResizeRequest
    from airbrowser_client.models.scale_data import ScaleData as ScaleData
    from airbrowser_client.models.scale_pool import ScalePool as ScalePool
    from airbrowser_client.models.screenshot_data import ScreenshotData as ScreenshotData
    from airbrowser_client.models.screenshot_response import ScreenshotResponse as ScreenshotResponse
    from airbrowser_client.models.select_request import SelectRequest as SelectRequest
    from airbrowser_client.models.snapshot_request import SnapshotRequest as SnapshotRequest
    from airbrowser_client.models.success_response import SuccessResponse as SuccessResponse
    from airbrowser_client.models.tabs_request import TabsRequest as TabsRequest
    from airbrowser_client.models.type_request import TypeRequest as TypeRequest
    from airbrowser_client.models.upload_file_request import UploadFileRequest as UploadFileRequest
    from airbrowser_client.models.url_data import UrlData as UrlData
    from airbrowser_client.models.url_response import UrlResponse as UrlResponse
    from airbrowser_client.models.wait_element_request import WaitElementRequest as WaitElementRequest
    from airbrowser_client.models.what_is_visible_result import WhatIsVisibleResult as WhatIsVisibleResult
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from airbrowser_client.api.browser_api import BrowserApi as BrowserApi
from airbrowser_client.api.health_api import HealthApi as HealthApi
from airbrowser_client.api.pool_api import PoolApi as PoolApi
from airbrowser_client.api.profiles_api import ProfilesApi as ProfilesApi

# import ApiClient
from airbrowser_client.api_response import ApiResponse as ApiResponse
from airbrowser_client.api_client import ApiClient as ApiClient
from airbrowser_client.configuration import Configuration as Configuration
from airbrowser_client.exceptions import OpenApiException as OpenApiException
from airbrowser_client.exceptions import ApiTypeError as ApiTypeError
from airbrowser_client.exceptions import ApiValueError as ApiValueError
from airbrowser_client.exceptions import ApiKeyError as ApiKeyError
from airbrowser_client.exceptions import ApiAttributeError as ApiAttributeError
from airbrowser_client.exceptions import ApiException as ApiException

# import models into sdk package
from airbrowser_client.models.action_result import ActionResult as ActionResult
from airbrowser_client.models.attribute_response import AttributeResponse as AttributeResponse
from airbrowser_client.models.base_response import BaseResponse as BaseResponse
from airbrowser_client.models.browser_config import BrowserConfig as BrowserConfig
from airbrowser_client.models.browser_created import BrowserCreated as BrowserCreated
from airbrowser_client.models.browser_creation_data import BrowserCreationData as BrowserCreationData
from airbrowser_client.models.browser_info_response import BrowserInfoResponse as BrowserInfoResponse
from airbrowser_client.models.browser_list import BrowserList as BrowserList
from airbrowser_client.models.browser_list_data import BrowserListData as BrowserListData
from airbrowser_client.models.check_element_request import CheckElementRequest as CheckElementRequest
from airbrowser_client.models.click_request import ClickRequest as ClickRequest
from airbrowser_client.models.combined_dialog_request import CombinedDialogRequest as CombinedDialogRequest
from airbrowser_client.models.combined_emulate_request import CombinedEmulateRequest as CombinedEmulateRequest
from airbrowser_client.models.combined_gui_click_request import CombinedGuiClickRequest as CombinedGuiClickRequest
from airbrowser_client.models.combined_scroll_request import CombinedScrollRequest as CombinedScrollRequest
from airbrowser_client.models.console_logs_request import ConsoleLogsRequest as ConsoleLogsRequest
from airbrowser_client.models.content_data import ContentData as ContentData
from airbrowser_client.models.content_response import ContentResponse as ContentResponse
from airbrowser_client.models.create_profile_request import CreateProfileRequest as CreateProfileRequest
from airbrowser_client.models.detect_coordinates_request import DetectCoordinatesRequest as DetectCoordinatesRequest
from airbrowser_client.models.detect_coordinates_result import DetectCoordinatesResult as DetectCoordinatesResult
from airbrowser_client.models.element_data_request import ElementDataRequest as ElementDataRequest
from airbrowser_client.models.error_response import ErrorResponse as ErrorResponse
from airbrowser_client.models.execute_data import ExecuteData as ExecuteData
from airbrowser_client.models.execute_request import ExecuteRequest as ExecuteRequest
from airbrowser_client.models.execute_response import ExecuteResponse as ExecuteResponse
from airbrowser_client.models.fill_form_request import FillFormRequest as FillFormRequest
from airbrowser_client.models.form_field import FormField as FormField
from airbrowser_client.models.health_status import HealthStatus as HealthStatus
from airbrowser_client.models.history_request import HistoryRequest as HistoryRequest
from airbrowser_client.models.logs_response import LogsResponse as LogsResponse
from airbrowser_client.models.mouse_request import MouseRequest as MouseRequest
from airbrowser_client.models.navigate_request import NavigateRequest as NavigateRequest
from airbrowser_client.models.network_logs_request import NetworkLogsRequest as NetworkLogsRequest
from airbrowser_client.models.performance_request import PerformanceRequest as PerformanceRequest
from airbrowser_client.models.pool_scaled import PoolScaled as PoolScaled
from airbrowser_client.models.pool_status_response import PoolStatusResponse as PoolStatusResponse
from airbrowser_client.models.press_keys_request import PressKeysRequest as PressKeysRequest
from airbrowser_client.models.profile_info import ProfileInfo as ProfileInfo
from airbrowser_client.models.profile_list_data import ProfileListData as ProfileListData
from airbrowser_client.models.profile_list_response import ProfileListResponse as ProfileListResponse
from airbrowser_client.models.profile_response import ProfileResponse as ProfileResponse
from airbrowser_client.models.resize_request import ResizeRequest as ResizeRequest
from airbrowser_client.models.scale_data import ScaleData as ScaleData
from airbrowser_client.models.scale_pool import ScalePool as ScalePool
from airbrowser_client.models.screenshot_data import ScreenshotData as ScreenshotData
from airbrowser_client.models.screenshot_response import ScreenshotResponse as ScreenshotResponse
from airbrowser_client.models.select_request import SelectRequest as SelectRequest
from airbrowser_client.models.snapshot_request import SnapshotRequest as SnapshotRequest
from airbrowser_client.models.success_response import SuccessResponse as SuccessResponse
from airbrowser_client.models.tabs_request import TabsRequest as TabsRequest
from airbrowser_client.models.type_request import TypeRequest as TypeRequest
from airbrowser_client.models.upload_file_request import UploadFileRequest as UploadFileRequest
from airbrowser_client.models.url_data import UrlData as UrlData
from airbrowser_client.models.url_response import UrlResponse as UrlResponse
from airbrowser_client.models.wait_element_request import WaitElementRequest as WaitElementRequest
from airbrowser_client.models.what_is_visible_result import WhatIsVisibleResult as WhatIsVisibleResult

""",
            name=__name__,
            doc=__doc__,
        )
    )
